version: 0.2

# Incoming environment variables
# ECR_ACCOUNT_ID
# ECR_IMAGE_TAG

phases:
  build:
    commands:
      - docker build -f infrastructure/Dockerfile -t ${ECR_IMAGE_TAG} .
  post_build:
    commands:
      - eval $(aws ecr get-login --registry-ids ${ECR_ACCOUNT_ID}) && docker push ${ECR_IMAGE_TAG}
